- name: haproxy
  apt:
    name: haproxy

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: create dynamic haproxy conf folder
  ansible.builtin.file:
    path: /etc/haproxy.cfg.d
    owner: root
    group: root
    state: directory

- name: tell haproxy to load cfg files from /etc/haproxy.cfg.d
  ansible.builtin.lineinfile:
    path: /etc/default/haproxy
    regexp: '^EXTRAOPTS='
    insertafter: '^#EXTRAOPTS='
    line: EXTRAOPTS=-f /etc/haproxy.cfg.d

- name: Copying the Directory's contents (sub directories/files)
  become: true 
  copy:
    src: "{{ playbook_dir }}/roles/haproxy/certificates"
    dest: /etc/haproxy/
    owner: root
    group: root        
    mode: 0644

- name: Add k8s API haproxy cfg
  template:
    src: k8s.cfg.j2
    dest: /etc/haproxy.cfg.d/k8s.cfg
    owner: root
    group: root
    mode: '0644'

- name: Add https haproxy cfg
  template:
    src: http_https.cfg.j2
    dest: /etc/haproxy.cfg.d/http_https.cfg
    #dest: /tmp/http_https.cfg
    owner: root
    group: root
    mode: '0644'
  vars:
    https_websites: "{{ lpp_websites }}"

- name: Add registry haproxy cfg
  template:
    src: registry.cfg.j2
    dest: /etc/haproxy.cfg.d/registry.cfg
    owner: root
    group: root
    mode: '0644'

- name: Add graphite haproxy cfg
  template:
    src: graphite.cfg.j2
    dest: /etc/haproxy.cfg.d/graphite.cfg
    owner: root
    group: root
    mode: '0644'


- name: Enable service haproxy
  service:
    name: haproxy
    enabled: yes
    state: restarted
