- name: "Check if kubectl is installed"
  command: dpkg -s kubectl kubeadm kubelet
  register: has_kubectl
  ignore_errors: true

- name: Install requirements
  ansible.builtin.package:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
  when: "'is not installed' in has_kubectl.stderr"

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a
    
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'

- name: add kubernetes repo
  shell: |
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
    apt-get update
  when: "'is not installed' in has_kubectl.stderr"

- name: Install kubectl, kubeadm and kubelet
  apt:
    name: 
      - kubelet=1.22.4-00
      - kubeadm=1.22.4-00
      - kubectl=1.22.4-00
  when: "'is not installed' in has_kubectl.stderr"

- name: Prevent kubernetes from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
      - kubelet 
      - kubeadm 
      - kubectl
  when: "'is not installed' in has_kubectl.stderr"