- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }} {{ item.split('.')[0] }}"
    state: present
  when: hostvars[item].ansible_host is defined
  loop: "{{ groups.all | reject('match', inventory_hostname) | list | flatten(1) }}"

- name: reduce systemd journal log level (1)
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^#MaxLevelStore=debug'
    line: 'MaxLevelStore=notice'


- name: reduce systemd journal log level (2)
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^#MaxLevelSyslog=debug'
    line: 'MaxLevelSyslog=notice'

- name: set resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: install collectd
  apt:
    name: collectd
    update_cache: yes

- name: set collectd.conf
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable service collectd
  service:
    name: collectd
    enabled: yes
    state: restarted

- name: add non-free
  apt_repository:
    repo: deb http://deb.debian.org/debian/ bullseye main non-free contrib
    state: present

- name: add non-free (src)
  apt_repository:
    repo: deb-src http://deb.debian.org/debian/ bullseye main non-free contrib
    state: present

- name: install nonfree firmwares 
  apt:
    name: 
      - firmware-linux-nonfree 
      - firmware-misc-nonfree

- name: install ipmi tools
  apt:
    name: openipmi
  when: is_dell_server